import './globals.css'
import { Inter } from 'next/font/google';
import Navbar from './Components/Navbar';
import { StreamingProvider } from './contexts/StremingContext';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='container mx-auto px-4 sm:px-6 lg:px-8'>
        <StreamingProvider>
        <Navbar/>
        {children}
        </StreamingProvider>
      </body>
    </html>
  );
}
